openapi: "3.0.2"

info:
  title: "Cities API"
  description: "My API for US postal code"
  version: "v1.0"

servers:
- url: http://localhost:3000
  description: My development server
- url: http://staging:3000
  description: My development server
- url: http://production:3000
  description: My development server

components:
  schemas:
    error:
      type: object
      properties:
        error:
          type: string
      required:
      - error
    
    city:
      type: object
      properties:
        _id:
          type: string
        city:
          type: string
        loc:
          type: array
          items:
            type: number
          minItems: 2
          maxItems: 2
        pop:
          type: integer
          minimum: 300
        state:
          type: string
          enum:
          - MA
          - RI
          - NH
          - ME
          - VT
          - CT
          - NY
          - NJ
          - PA
          - DE
          - DC
          - MD
          - VA
          - WV
          - NC
          - SC
          - GA
          - FL
          - AL
          - TN
          - MS
          - KY
          - OH
          - IN
          - MI
          - IA
          - WI
          - MN
          - SD
          - ND
          - MT
          - IL
          - MO
          - KS
          - NE
          - LA
          - AR
          - OK
          - TX
          - CO
          - WY
          - ID
          - UT
          - AZ
          - NM
          - NV
          - CA
          - HI
          - OR
          - WA
          - AK
          - SG
      required:
      - city
      - loc
      - pop
      - state

paths:
  /api/state/{stateId}:
    get:
      description: Return a list of cities from the state in URI
      operationId: getCitiesFromState
      parameters:
      - name: stateId
        in: path
        required: true
        schema:
          $ref: "city-schema.json#/definitions/state"
      responses:
        200: 
          description: Success
          content:
            application/json:
              schema:
                  type: array
                  items:
                    type: string
        400:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
                
  /api/states:
    get:
      description: Return a list of valid 2 character states
      operationId: getStates
      responses: 
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "city-schema.json#/definitions/state"
        400:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  
  /api/city:
    post:
      description: Add new city
      operationId: addNewCity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/city"
      responses: 
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/city"
        400:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"