openapi: "3.0.2"

info:
  title: "Cities API"
  description: "My API for US postal code"
  version: "v1.0"

servers:
- url: http://localhost:3000
  description: My development server
- url: http://staging:3000
  description: My development server
- url: http://production:3000
  description: My development server

components:
  schemas:
    error:
      type: object
      properties:
        error:
          type: string
      required:
      - error

paths:
  /api/state/{stateId}:
    get:
      description: Return a list of cities from the state in URI
      operationId: getCitiesFromState
      parameters:
      - name: stateId
        in: path
        required: true
        schema:
          $ref: "city-schema.json#/definitions/state"
      responses:
        200: 
          description: Success
          content:
            application/json:
              schema:
                  type: array
                  items:
                    type: string
        400:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
                
  /api/states:
    get:
      description: Return a list of valid 2 character states
      operationId: getStates
      responses: 
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "city-schema.json#/definitions/state"
        400:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  
  /api/city:
    post:
      description: Add new city
      operationId: addNewCity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "city-schema.json"
      responses: 
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: "city-schema.json"
        400:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  